{% set version = "2016.8.31" %}

package:
  name: certifi
  version: {{ version }}

source:
  fn: certifi-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/certifi/certifi-{{ version }}.tar.gz
  sha256: f7708a42d86f29ccc7c8c4ff9d34a8d854d8d78eb2973d1f28406bb43d6b8919

build:
  number: 0
  script: python setup.py install
  skip: True  # [py27]
  skip: True  # [py34]
  skip: True  # [py35]

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
  license_file: LICENSE
  summary: Python package for providing Mozilla's CA Bundle.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - sigmavirus24
    - ocefpaf
